version: "3"
services:
  selenium-hub:
    image: selenium/hub
    container_name: selenium-hub
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome
    depends_on:
      - selenium-hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444
  pwnedtest:
    image: vidhyadocker/pwnedtest:test
    container_name: pwnedtest
    depends_on:
      - chrome
    environment:
      - SELENIUM_HUB=selenium-hub